[project]
name = "ghcn-showcases"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "polars>=1.32.3",
    "xlsxwriter>=3.2.5",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
